### ISSUE TITLE
undefined method `include?' for nil:NilClass 

### ISSUE THREAD

**Issue by greyblake** [datamapper/dm-sqlite-adapter#6]
I've got this error when I call `Model.new(:param => "value")` or `Model.create(:param => "value"`)
## Exception

```
/home/blake/.rvm/gems/ruby-1.8.7-p352@project/gems/dm-core-1.2.0/lib/dm-core/resource.rb:332:in `attributes=': undefined method `include?' for nil:NilClass (NoMethodError)
from /home/blake/.rvm/gems/ruby-1.8.7-p352@project/gems/dm-core-1.2.0/lib/dm-core/resource.rb:329:in `each'
from /home/blake/.rvm/gems/ruby-1.8.7-p352@project/gems/dm-core-1.2.0/lib/dm-core/resource.rb:329:in `attributes='
from /home/blake/.rvm/gems/ruby-1.8.7-p352@project/gems/dm-core-1.2.0/lib/dm-core/resource.rb:748:in `initialize'
from /home/blake/.rvm/gems/ruby-1.8.7-p352@project/gems/dm-validations-1.2.0/lib/dm-validations.rb:129:in `new'
from /home/blake/.rvm/gems/ruby-1.8.7-p352@project/gems/dm-validations-1.2.0/lib/dm-validations.rb:129:in `create'
```

It works fine when I use memory as a storage. But when I use a file it fails.
I set up storage like this:

```
    DataMapper.setup(:default, "sqlite:/path/to/db.sqlite")
    DataMapper.finalize
    DataMapper.auto_migrate!
```
## Env
- ruby1.8.7
- uname -a:  `Linux alice 2.6.32-5-amd64 #1 SMP Thu Nov 3 03:41:26 UTC 2011 x86_64 GNU/Linux`
- dm, version 1.2.0

**Comment by greyblake** [comment]
Looks like a forgot to call `DataMapper.finalize`. Sorry for the disturbance.
